"Name: \TY:CL_RIS_SHM_METADATA\ME:INITIALIZE\SE:BEGIN\EI
ENHANCEMENT 0 ZCL_RIS_SHM_METADATA_INITIALIZ.
    IF zz_initialize( ).
      RETURN.
    ENDIF.
    ASSERT 1 = 1. " DEBUG HELPER
ENDENHANCEMENT.
