"Name: \TY:CL_RIS_SHM_METADATA\ME:CONSTRUCTOR\SE:BEGIN\EI
ENHANCEMENT 0 ZCL_RIS_SHM_METADATA_CONSTRUCT.
    IF zz_constructor( ).
      RETURN.
    ENDIF.
    ASSERT 1 = 1. " DEBUG HELPER
ENDENHANCEMENT.
